<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>

    <PackageReference Include="NServiceBus" Version="10.2.7" />
    <PackageReference Include="NServiceBus.AzureFunctions.Worker.ServiceBus" Version="7.1.1" />
    <PackageReference Include="NServiceBus.Extensions.Hosting" Version="4.1.0" />
    <PackageReference Include="NServiceBus.Newtonsoft.Json" Version="5.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.47" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="5.2.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.9" />
    <PackageReference Include="SFA.DAS.Encoding" Version="1.1.76" />
    <PackageReference Include="System.Net.Security" Version="4.3.2" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.9" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.21.0" />

    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="SFA.DAS.Configuration.AzureTableStorage" Version="3.0.84" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.Reservations.Application\SFA.DAS.Reservations.Application.csproj" />
    <ProjectReference Include="..\SFA.DAS.Reservations.Data\SFA.DAS.Reservations.Data.csproj" />
    <ProjectReference Include="..\SFA.DAS.Reservations.Domain\SFA.DAS.Reservations.Domain.csproj" />
  </ItemGroup>

</Project>
