<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Azure.Search.Documents" Version="11.7.0-beta.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.9" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NServiceBus" Version="9.2.3" />
    <PackageReference Include="SFA.DAS.Account.Api.Types" Version="1.6.3195" />
    <PackageReference Include="SFA.DAS.CommitmentsV2.Messages" Version="8.29.1" />
    <PackageReference Include="SFA.DAS.EmployerAccounts.Messages" Version="1.6.3195" />
    <PackageReference Include="SFA.DAS.EmployerFinance.Messages" Version="2.0.3" />
    <PackageReference Include="SFA.DAS.ProviderRelationships.Messages" Version="4.0.19" />
    <PackageReference Include="SFA.DAS.Reservations.Messages" Version="0.2.1" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.9" />
    <PackageReference Include="System.Security.Cryptography.X509Certificates" Version="4.3.2" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.9" />
    <PackageReference Include="System.Text.Json" Version="10.0.9" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
  </ItemGroup>

</Project>
